[workspace]
resolver = "2"

members = ["day*"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
anyhow = "1.0.75"
nom = "7.1.3"